version: '3'
services:
  #publisher service
  publisher:
    image: openjdk:8u171-jdk-alpine3.8
    volumes:
      - "$HOME/git/maven-miner/files/maven-indexer:/dist"
#    deploy:
#      update_config:
#        delay: 10s
#      restart_policy:
#        condition: on-failure
    depends_on:
      - neo4j
      - rabbitmq
    command: /dist/run-producer.sh -queue localhost:5672
  #consumer service
  consumer:
    image: openjdk:8u171-jdk-alpine3.8
    volumes:
      - "$HOME/git/maven-miner/files/maven-aether:/dist"
#    deploy:
#      update_config:
#        delay: 10s
#      restart_policy:
#        condition: on-failure
    depends_on:
      - neo4j
      - rabbitmq
    command: /dist/run-consumer.sh -db localhost:7687 -queue localhost:5672
  #neo4j service
  neo4j:
    image: neo4j:3.0
    volumes:
      - "$HOME/neo4j-server/data:/data"
      - "$HOME/neo4j-server/logs:/logs"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
  #rabbit mq service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
